server:
  port: 8080

task:
  service:
    url: http://task-service:8080

user:
  service:
    url: http://user-service:8080

internal:
  token: d48f1e3a-72e4-4a41-9df5-6f9b9ea71234

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sakinabaranwala123@gmail.com
    password: vjxkiykseydoneir
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
