apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*.log

    processors:
      - add_kubernetes_metadata: ~

    output.logstash:
      hosts: ["logstash:5044"]

    setup.kibana:
      host: "kibana:5601"