server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: task_db

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator