replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "300m"
    memory: "1Gi"

ingress:
  enabled: false

elasticsearchHosts: "http://elasticsearch-master:9200"
