apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: sakina2726/task-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20        # Give it more time if your app starts slowly
            periodSeconds: 10              # Probe every 10 seconds
            timeoutSeconds: 5              # Wait up to 5 seconds for a response
            failureThreshold: 5            # Fail only after 5 consecutive failures
            successThreshold: 1