apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nlp-service
  template:
    metadata:
      labels:
        app: nlp-service
    spec:
      containers:
        - name: nlp-service
          image: sakina2726/service-nlp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10