- name: Setup Task Manager Project
  hosts: localhost
  become: true
  become_method: sudo
  vars_files:
    - group_vars/vault.yml
  roles:
    - docker
    - docker_push
    - project
  collections:
    - community.docker